branches:
  only:
    - master
language: python
python:
    - 2.7
sudo: required
addons.apt.packages:
    - python-libvirt
    - python-yaml
    - make
before_install:
    - wget  http://sourceforge.net/projects/ssdeep/files/ssdeep-2.13/ssdeep-2.13.tar.gz
    - tar -zxvf ssdeep-2.13.tar.gz
    - cd ssdeep-2.13
    - ./configure && make
    - sudo make install
    - cd ..
    - sed -i 's/connection = .*/connection =/' conf/cuckoo.conf
install:
    - pip install -r requirements.txt
    - ./utils/community.py -wafb monitor && ./utils/community.py -wafb 2.0
script:
    - ls -la
    - python cuckoo.py --debug --test
    #- nosetests
